# Metadata of this classic Heroku buildpack (bin/detect, bin/compile, bin/release)

[buildpack]
name = "FrankenPHP"
version = "0.2.0"
homepage = "https://github.com/katchmk/heroku-buildpack-frankenphp"
description = "Heroku buildpack for FrankenPHP - a modern PHP application server"
keywords = ["php", "frankenphp", "caddy", "heroku"]

[[buildpack.licenses]]
type = "MIT"
